# Generated by Django 2.1.5 on 2019-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('stu_no', models.CharField(max_length=100, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=100, verbose_name='性别')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('portrait', models.ImageField(upload_to='static/user_portrait')),
                ('mail', models.CharField(max_length=100, verbose_name='邮箱')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='状态/个性签名')),
            ],
        ),
    ]
