# Generated by Django 2.1.5 on 2019-01-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='portrait',
            field=models.ImageField(upload_to='static/user_portrait'),
        ),
    ]
