# Generated by Django 2.1.5 on 2019-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_site', '0002_auto_20190127_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='状态/个性签名'),
        ),
    ]
